data-path="/opt/besu/data";
genesis-file="/opt/besu/config/genesis.json";
network-id=1337;
rpc-http-enabled=true;
rpc-http-host="0.0.0.0";
rpc-http-port=8545;
rpc-ws-enabled=true;
rpc-ws-host="0.0.0.0";
rpc-ws-port=8546;
host-whitelist=["*"];
rpc-http-cors-origins=["*"];
p2p-port=30303;